"use client";

import React from 'react';
import { FileText, Sparkles } from 'lucide-react';

interface NarrativeCardProps {
  story: string;
}

export default function NarrativeCard({ story }: NarrativeCardProps) {
  return (
    <div className="bg-white rounded-[24px] p-6 card-shadow h-full flex flex-col">
      <div className="flex items-center gap-3 mb-4">
        <div className="bg-[#EAF2FF] p-2 rounded-lg text-[#1D4ED8]">
          <FileText className="w-5 h-5" />
        </div>
        <h3 className="font-semibold text-[#172B4D] text-lg">Clinical Narrative</h3>
      </div>
      
      <div className="flex-1 text-[#172B4D] text-sm leading-relaxed whitespace-pre-line overflow-y-auto pr-2">
        {story || "No clinical narrative available. Run analysis to generate a story."}
      </div>
      
      <div className="mt-4 pt-4 border-t border-gray-100 flex items-center justify-center">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-purple-50 text-purple-700 rounded-full text-xs font-medium border border-purple-100">
          <Sparkles className="w-3.5 h-3.5" />
          Generated by AI Clinical Storyteller (BART)
        </div>
      </div>
    </div>
  );
}
